name: Mirror to Gitee Repo
#同步他人github到gitee
on:
  push: # 有 push 代码的时候会执行
    branches: [ main ]
  #pull_request: # 有 pull_request 代码的时候会执行
    #branches: [ main ]
  schedule: 
    # 每天9点跑一次
    - cron:  '0 1 * * *'

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Private Key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "StrictHostKeyChecking no" >> ~/.ssh/config
      - name: Push Mirror
        env:
          SOURCE_REPO: 'https://github.com/JDWXX/jd_job.git'
          DESTINATION_REPO: 'git@gitee.com:redte4/jd_job.git'
        run: |
          git clone --mirror "$SOURCE_REPO" && cd `basename "$SOURCE_REPO"`
          git remote set-url --push origin "$DESTINATION_REPO"
          git fetch -p origin
          git for-each-ref --format 'delete %(refname)' refs/pull | git update-ref --stdin
          git push --mirror
